In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Ronald_Evans.txt to Ronald_Evans.txt
User uploaded file "Ronald_Evans.txt" with length 38380 bytes


In [ ]:
text_file = "Ronald_Evans.txt" 

In [ ]:
def clean_text(x):
    pattern = r'[^a-zA-z0-9\s]'
    x = re.sub(pattern, '', x)

In [ ]:
from nltk.corpus import stopwords

In [ ]:
a_file = open("Ronald_Evans.txt", "r")

stop_words = set(stopwords.words('english')) 

line = a_file.read()
words = line.split() 
for r in words: 
    if not r in stop_words: 
        appendFile = open('Ronald_Evans.txt','a') 
        appendFile.write(" "+r) 
        appendFile.close() 

a_file = appendFile
doc2vec_list = []
a_file = open("Ronald_Evans.txt", "r")


list_of_lists = []
for line in a_file:
  #line = line.lower()
  stripped_line = line.lower().strip()
  line_list = stripped_line.split('.')
  #print(line_list)
  for sentence in line_list:
    clean_text(sentence)
    sentence = re.sub(r"machine {1}learning", lambda x: ''.join(p for p in x.group(0).title() if not p.isspace()), sentence)
    sentence = re.sub(r"nuclear {1}receptor", lambda x: ''.join(p for p in x.group(0).title() if not p.isspace()), sentence)

    sentence = re.sub(r"deep {1}learning", lambda x: ''.join(p for p in x.group(0).title() if not p.isspace()), sentence)
    sentence = re.sub(r"[(){}]", '', sentence)
    doc2vec_list.append(sentence)
    list_of_lists.append(sentence.split())
    
a_file.close()

print(list_of_lists)

[['analyses', 'of', 'steroid', 'receptors', 'are', 'important', 'for', 'understanding', 'molecular', 'details', 'of', 'transcriptional', 'control,', 'as', 'well', 'as', 'providing', 'insight', 'as', 'to', 'how', 'an', 'individual', 'transacting', 'factor', 'contributes', 'to', 'cell', 'identity', 'and', 'function'], ['these', 'studies', 'have', 'led', 'to', 'the', 'identification', 'of', 'a', 'superfamily', 'of', 'regulatory', 'proteins', 'that', 'include', 'receptors', 'for', 'thyroid', 'hormone', 'and', 'the', 'vertebrate', 'morphogen', 'retinoic', 'acid'], ['although', 'animals', 'employ', 'complex', 'and', 'often', 'distinct', 'ways', 'to', 'control', 'their', 'physiology', 'and', 'development,', 'the', 'discovery', 'of', 'receptor-related', 'molecules', 'in', 'a', 'wide', 'range', 'of', 'species', 'suggests', 'that', 'mechanisms', 'underlying', 'morphogenesis', 'and', 'homeostasis', 'may', 'be', 'more', 'ubiquitous', 'than', 'previously', 'expected'], ['the', 'steroid', 'and', 'th

In [ ]:
model = gensim.models.Word2Vec(list_of_lists, size=3, window=100, min_count=2, workers=10)
#model.train(list_of_lists,total_examples=len(list_of_lists),epochs=10)

In [ ]:
model.wv.similar_by_word('NuclearReceptor')

[('mediators', 0.9999820590019226),
 ('regulation', 0.9999625086784363),
 ('approach', 0.9999582767486572),
 ('insulin-sensitizing', 0.9999515414237976),
 ('neural', 0.9999455213546753),
 ('reprogramming', 0.9999341368675232),
 ('tissue-specific', 0.9999121427536011),
 ('factor', 0.9999119639396667),
 ('40-fold', 0.9998988509178162),
 ('energy', 0.9998939037322998)]

In [ ]:
#v1 = model.wv['MachineLearning']
#v2 = model.wv['DeepLearning']
v3 = model.wv['NuclearReceptor']
#v3 = np.zeros(3)  #physics
v4 = np.zeros(3)  #molecular biology
#v3 = model.wv['physics']
#print(v2)

import numpy as np

def cosine_similarity(a, b):
    nominator = np.dot(a, b)
    a_norm = np.sqrt(np.sum(a**2))
    b_norm = np.sqrt(np.sum(b**2))
    denominator = a_norm * b_norm
    cosine_similarity = nominator / denominator
    if(math.isnan(cosine_similarity)):
      return 0  
    return cosine_similarity

#cosine_similarity(v1, v2)

In [ ]:
topic_words = ctm_topic_lists
ctm_topic_vectors = []

for word_list in topic_words:
  ctm_topic_vector_single = []
  for word in word_list:
    model.train([[word]], total_examples=1, epochs=1)
    try:
      topic_word_vector = model.wv[word]
    except:
      topic_word_vector = [0]*3
    #topic_word_vector = model.wv[word]
    ctm_topic_vector_single.append(topic_word_vector)
    print(topic_word_vector)
    print(" ")
  ctm_topic_vectors.append(ctm_topic_vector_single)
  print("----------")

[-0.5480239  -0.13065872  1.3507429 ]
 
[-0.10781173 -0.21595682  0.6185095 ]
 
[-0.08067403 -0.11038478  0.19843979]
 
[-0.55460954 -0.29025978  1.4864074 ]
 
[-0.2653666   0.02302211  0.3750414 ]
 
----------
[-0.34634253 -0.2637723   1.2545104 ]
 
[-0.10679158  0.04565771  0.13477314]
 
[-0.8026022  -0.26382235  1.8457088 ]
 
[-0.2018399   0.02477991  0.33490708]
 
[-0.50853986 -0.31712374  1.2716719 ]
 
----------
[-0.49678242 -0.31656894  1.3025914 ]
 
[0, 0, 0]
 
[-0.28948647  0.07200871  0.2699251 ]
 
[-0.28359345 -0.14212286  0.81156933]
 
[-0.30914792  0.0070953   0.43717468]
 
----------
[0, 0, 0]
 
[-0.11340261 -0.0091679   0.34240422]
 
[-0.41817802 -0.14322871  0.86639905]
 
[-0.42357895 -0.16751687  1.18249   ]
 
[ 0.12800242  0.06831166 -0.03934917]
 
----------
[-0.26472923 -0.16007218  1.0269237 ]
 
[-0.12723872 -0.14270699  0.37485874]
 
[-0.7835292  -0.48390916  2.2184434 ]
 
[-0.01490197 -0.0461726   0.2735389 ]
 
[-0.21004984 -0.22248542  0.415693  ]
 
----------


In [ ]:
for list_of_vector in ctm_topic_vectors:
  ans1 = 0
  ans2 = 0
  ans3 = 0
  ans4 = 0
  for vector in list_of_vector:
    ans1 = ans1 + cosine_similarity(np.array(vector), v1)
    #ans2 = ans2 + cosine_similarity(np.array(vector), v2)
    #ans3 = ans3 + cosine_similarity(np.array(vector), v3)
    #ans4 = ans4 + cosine_similarity(np.array(vector), v4)
  print(ans1)
  #print(ans2)
  #print(ans3)
  #print(ans4)
  print("\n")

3.0886090695858


3.646820306777954


2.8799296021461487


1.953345775604248


2.869239002466202




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in double_scalars
  app.launch_new_instance()
